[package]
name = "gv-web"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
gv-app.workspace = true
gv-config.workspace = true
gv-graph.workspace = true
gv-gui.workspace = true

anyhow.workspace = true
log.workspace = true
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
console_log = "1"
getrandom = { version = "0.4", features = ["wasm_js"] }
